name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Add Helm repository
        run: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Update Helm repositories
        run: helm repo update

      - name: Install kube-prometheus-stack
        run: helm install kube-prometheus prometheus-community/kube-prometheus-stack -f promn.yaml

      - name: Deploy nginx
        run: kubectl apply -f deployment.yaml

    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      KUBERNETES_SERVER: ${{ secrets.KUBERNETES_SERVER }}
      KUBERNETES_SERVICE_ACCOUNT_TOKEN: ${{ secrets.KUBERNETES_SERVICE_ACCOUNT_TOKEN }}
