name: Docker Image CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean up old packages
        run: |
          sudo apt-get autoremove -y
          sudo apt-get clean

      - name: Fix dependency issues
        run: |
          sudo apt-get update
          sudo apt-get install -f

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo 'PATH=$PATH:/home/runner/.yandex-cloud/bin' >> $GITHUB_ENV
          echo 'PATH=$PATH:/home/runner/.yandex-cloud/bin' >> ~/.bashrc
          source ~/.bashrc
          yc --version
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest   
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl config view

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/nginx nginx=${{ secrets.DOCKER_USERNAME }}/my-image-name:latest

