name: Build and Deploy

on:
  push:
    branches:
      - main
      - master
  create:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/app:latest
            ${{ secrets.DOCKER_USERNAME }}/app:${{ github.sha }}
            ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && format('{0}/app:main', secrets.DOCKER_USERNAME) || '' }}
            ${{ github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v') && format('{0}/app:{1}', secrets.DOCKER_USERNAME, github.ref_name) || '' }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v2
        with:
          version: 'latest'

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/nginx nginx=${{ secrets.DOCKER_USERNAME }}/app:latest -n default
    env:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      KUBERNETES_SERVICE_ACCOUNT_TOKEN: ${{ secrets.KUBERNETES_SERVICE_ACCOUNT_TOKEN }}
