# .github/workflows/docker-build-and-push.yml
name: Docker Image CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag my-image-name:latest
          docker tag my-image-name:latest ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
