name: Docker Image CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=my-image-name:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_TAG
        docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
