name: Deploy to Kubernetes

on:
  push:
    tags:
      - 'v*.*.*'  # Срабатывает на теги вида v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.ref_name }}

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo 'source "/home/runner/.bashrc"' >> $GITHUB_ENV
          echo 'export PATH=$PATH:$HOME/yandex-cloud/bin' >> $GITHUB_ENV
      - name: Use Yandex Cloud CLI
        run: |
          /home/runner/yandex-cloud/bin/
          yc --version
      - name: Configure Yandex Cloud CLI
        run: |
          yc config set token ${{ secrets.YC_TOKEN }}
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
        env:
          PATH: $HOME/yandex-cloud/bin:$PATH

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl config view

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl config view

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-deployment my-container=cr.yandex/${{ secrets.YC_CLOUD_ID }}/${{ secrets.YC_FOLDER_ID }}:${{ github.ref_name }}
          kubectl rollout status deployment/my-deployment
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
