# .github/workflows/deploy-to-kubernetes.yml
name: Deploy to Kubernetes

on:
  push:
    tags:
      - 'v*.*.*'  # Срабатывает на теги вида v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  

      - name: Build and Push Docker Image with Tag
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cr.yandex/${{ secrets.YC_CLOUD_ID }}/${{ secrets.YC_FOLDER_ID }}:${{ github.ref_name }}

      - name: Set up Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo 'export PATH=$HOME/yandex-cloud/bin:$PATH' >> $GITHUB_ENV
          source $GITHUB_ENV
      - name: Use Yandex Cloud CLI
        run: |
         source $GITHUB_ENV
         yc --version
      - name: Configure Yandex Cloud CLI
        run: |
          yc config set token ${{ secrets.YC_TOKEN }}
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl config view

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-deployment my-container=cr.yandex/${{ secrets.YC_CLOUD_ID }}/${{ secrets.YC_FOLDER_ID }}:${{ github.ref_name }}
          kubectl rollout status deployment/my-deployment
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
